# Generated by Django 3.1.2 on 2020-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
