# Generated by Django 3.1.2 on 2020-11-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201108_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='product_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='shop.subcategory'),
        ),
    ]
