# Generated by Django 3.1.2 on 2020-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201108_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('person_email', models.EmailField(max_length=254)),
                ('person_phone', models.BigIntegerField()),
                ('person_msg', models.TextField()),
            ],
        ),
    ]
